### PR TITLE
Added code to filter for sessions with a given stimulation

### PR DESCRIPTION
**Pull request by Tobias-Ruff**
This might be useful when using optogenetics and other perturbations.
It also still works totally fine, if a project contains no stimulation files because it might no use them.
The code doesn't need to be merged, just in case it is helpful for others.
I also adapted the documentation in the `man` directory, but haven't added any tests yet, which might actually be good.

### CODE REVIEW

**Comment by Tobias-Ruff** [comment]
Hi Kevin,

Wow, that was really quick. Thanks for your answer.
This sounds good. I am just starting to use the package and the changes I made might be problematic.
I will check carefully again.

**Comment by kevin-allen** [comment]
Hi Tobias,
Thanks for cleaning the changes. It looks like it can be merged with the base branch. Are you done with it?

Also, I presumed you used devtool::documentation() to update the documentation.

As soon as I get your ok I will merge your pull request.

**Comment by Tobias-Ruff** [comment]
Hi Kevin,

Thanks for your answer. I ran the `documentation` function of the `devtool` package to update the documentation automatically in order to avoid manual changes and then did a `R CMD check relectro_0.0.0.9002.tar.gz` to make sure everything works correctly.
You could merge the code, but since it implements a feature (including stimulation files), which not everybody needs, I could also imagine to just keep the changes as a fork.

**Comment by kevin-allen** [comment]
I would prefer to merge it with the base as it is a useful features that other might need in the future. I will merge it and check that it does not cause problem when there is no stimulation file.

**Pull request merged**
